### ISSUE TITLE
Symlink to ~/.zshrc is invalid

### ISSUE THREAD

**Issue by stefan131** [hugovandevliert/dotfiles#1]
In `setup.sh:12` a symlink for `~/.zshrc` is created.
The current line, `ln -sfn "$PWD.zshrc" "$HOME/.zshrc"`, results in the following symlink: `.zshrc -> ~/dotfiles.zshrc`.
I think this line should be changed to `ln -sfn "$PWD/.zshrc" "$HOME/.zshrc"`

<img width="537" alt="image" src="https://user-images.githubusercontent.com/9026163/222363504-6dd88d43-d2d0-4e5a-b4d1-8a171d7f9e3f.png">

**Comment by hugovandevliert** [comment]
Hey @stefan131, thanks for the heads-up! I've addressed this in https://github.com/hugovandevliert/dotfiles/commit/211268d50a795c7ba700a94ce4a47ca15a594612.
